// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFbollTxkTOSa4UpRcj4qH6y8-O4-TiI',
    appId: '1:295478432900:web:5978089514807db6e89ed1',
    messagingSenderId: '295478432900',
    projectId: 'netflix-fd617',
    authDomain: 'netflix-fd617.firebaseapp.com',
    storageBucket: 'netflix-fd617.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg47eGlIAM8gdDWu1PE1JFHrEwB0LaJhU',
    appId: '1:295478432900:android:2c8ef7c6400c47d9e89ed1',
    messagingSenderId: '295478432900',
    projectId: 'netflix-fd617',
    storageBucket: 'netflix-fd617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9GfKKfD1lBi4M4ewpR_c9Va87OaAsBk',
    appId: '1:295478432900:ios:971774b560cd8d7be89ed1',
    messagingSenderId: '295478432900',
    projectId: 'netflix-fd617',
    storageBucket: 'netflix-fd617.appspot.com',
    iosClientId: '295478432900-0r9tti3vup4fomvrfnho4ikk4lctlevm.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiCalls',
  );
}
